port: 41337
updateCheckInterval: 0
auth:
  port: 41338
  cliClientId: BlkYEHauoKWvGcN2my1TGlqh5dHHuW30
  apertureClientId: dbiUqhi4U6m7oYpEPKzJbJu3ZHVFImf0
  registryClientId: 7Iav52mxENMvUGAj55zBJLaS3CRjj2jp
services:
  app: https://app.qubit.com
  registry: https://registry.qubit.com
  auth: https://auth.qubit.com
logger:
  level: info
